[local]
localhost

[mongodb]
mongodb.sairamdaws.online

[redis]
redis.sairamdaws.online

[mysql]
mysql.sairamdaws.online

[rabbitmq]
rabbitmq.sairamdaws.online

[catalogue]
catalogue.sairamdaws.online
