[local]
localhost

[mongodb]
mongodb.sairamdaws.online

[redis]
redis.sairamdaws.onine

[mysql]
mysql.sairamdaws.online

[rabbitmq]
rabbitmq.sairamdaws.online

[catalouge]
catalouge.sairamdaws.online
